default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  primary:
    <<: *default
    database: <%= ENV['DB_NAME'] %>_production
  cache:
    <<: *default
    database: <%= ENV['DB_NAME'] %>_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV['DB_NAME'] %>_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['DB_NAME'] %>_production_cable
    migrations_paths: db/cable_migrate